'language_extensions': []
'steps':
- 'imports':
    'align': 'group'
- 'language_pragmas':
    'style': 'compact_line'
    'remove_redundant': |-
      true
- 'trailing_whitespace': {}
'columns': |-
  80
