name:                halg-algorithms
version:             0.6.0.0
github:              "konn/halg-groebner"
license:             BSD3
author:              "Hiromi ISHII"
maintainer:          "konn.jinro _at_ gmail.com"
copyright:           "2018 (c) Hiromi ISHII"

extra-source-files:
- README.md
- ChangeLog.md

tested-with: |
  GHC == 8.4.3, GHC == 8.6.5, GHC == 8.8.2, GHC == 8.10.1

# Metadata used when publishing your package
synopsis:            Algorithms related to Gröbner basis, part of halg computational algebra suite.
category:            Math

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the project Web Site <https://konn.github.io/computational-algebra>

default-extensions:
- CPP
- DataKinds
- FlexibleContexts
- FlexibleInstances
- GADTs
- MultiParamTypeClasses
- OverloadedLabels
- PolyKinds
- TypeFamilies
- TypeInType
- UndecidableInstances  

dependencies:
- MonadRandom
- algebra
- base >= 4.7 && < 5
- dlist
- halg-core
- halg-polynomials
- halg-heaps
- heaps
- semigroups
- sized

library:
  source-dirs: src
  other-modules:
  - Algebra.Algorithms.FGLM
  ghc-options: ["-Wall", "-O2"]
  dependencies:
  - algebraic-prelude
  - containers
  - control-monad-loop
  - convertible
  - equational-reasoning
  - ghc-typelits-presburger
  - singletons-presburger
  - singletons
  - type-natural
  - equational-reasoning
  - foldl
  - ghc-typelits-knownnat
  - halg-matrices
  - hmatrix
  - lens
  - matrix
  - monad-loops
  - mono-traversable
  - mtl
  - parallel
  - reflection
  - sized
  - vector
  default-extensions:
  - NoImplicitPrelude

_prof-settings: &prof-settings
  source-dirs:
  - app
  - shared
  other-modules:
  - Cases
  ghc-options:
  - -Wall
  - -threaded
  - -rtsopts
  - -O2
  - -with-rtsopts=-N
  - -fprof-auto
  - -fprof-cafs
  dependencies:
  - halg-core
  - halg-polynomials
  - halg-algorithms
  - deepseq
  - ghc-typelits-knownnat
  - reflection
  - vector

executables:
  f5-prof:
    main:                f5-prof.hs
    <<: *prof-settings
  f4-prof:
    main:                f4-prof.hs
    <<: *prof-settings
  std-prof:
    main:                std-prof.hs
    <<: *prof-settings
  katsura-prof:
    main:                katsura-prof.hs
    <<: *prof-settings

tests:
  halg-algorithms-specs:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -Wall
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -fsimplifier-phases=3 
    - -fmax-simplifier-iterations=20
    - -rtsopts
    dependencies:
    - HUnit
    - ghc-typelits-knownnat
    - halg-core-test
    - halg-polynomials
    - singletons-presburger
    - singletons
    - halg-algorithms
    - halg-bridge-singular
    - QuickCheck
    - convertible
    - containers
    - equational-reasoning
    - hspec
    - lens
    - matrix
    - ghc-typelits-knownnat
    - quickcheck-instances
    - reflection
    - smallcheck
    - type-natural
    - vector
    - hspec-discover

_heavy_bench: &heavy_bench
  source-dirs:
  - bench
  - shared
  other-modules: Cases
  dependencies:
  - halg-algorithms
  - gauge
  - parallel
  - containers
  - folds
  - foldl
  - lens
  - reflection
  - vector
  - deepseq
  - ghc-typelits-knownnat
  ghc-options:
  - -Wall
  - -O2
  - -threaded
  - -rtsopts
  - -with-rtsopts=-N  

benchmarks:
  homog-bench:
    source-dirs:  bench
    main:         homog-bench.hs
    dependencies:
    - halg-algorithms
    - gauge
    - parallel
    ghc-options:
    - -Wall
    - -O2
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
  ordering-bench:
    source-dirs:  bench
    buildable: false
    main:         ordering-bench.hs
    dependencies:
    - halg-algorithms
    - gauge
    - parallel
    - containers
    - folds
    - foldl
    - lens
    - vector
    ghc-options:
    - -Wall
    - -O2
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
  sugar-hilb-bench:
    source-dirs:  bench
    main:         sugar-hilb.hs
    dependencies:
    - halg-algorithms
    - gauge
    - parallel
    - containers
    - folds
    - foldl
    - lens
    ghc-options:
    - -Wall
    - -O2
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N

  sugar-paper-bench:
    main: sugar-paper.hs
    source-dirs:
    - bench
    dependencies:
    - QuickCheck
    - constraints
    - containers
    - deepseq
    - gauge
    - halg-algorithms
    - halg-core
    - halg-core-test
    - matrix
    - parallel
    - process
    - reflection
    - sized
    - vector
    ghc-options:
    - -O2
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N

  quot-non-rewrite-bench:
    main: quot-non-rewrite-bench.hs
    other-modules:
    - Cases
    source-dirs:
    - bench
    - shared
    dependencies:
    - ghc-typelits-knownnat
    - halg-core
    - halg-core-test
    - halg-algorithms
    - constraints
    - containers
    - vector
    - gauge
    - reflection
    - deepseq
    - matrix
    - parallel
    - process
    - sized
    - QuickCheck
    ghc-options:
    - -O2
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N

  quot-rewrite-bench:
    main: quot-rewrite-bench.hs
    other-modules:
    - Cases
    source-dirs:
    - bench
    - shared
    dependencies:
    - ghc-typelits-knownnat
    - halg-core
    - halg-core-test
    - halg-algorithms
    - constraints
    - containers
    - vector
    - gauge
    - deepseq
    - matrix
    - reflection
    - parallel
    - process
    - sized
    - QuickCheck
    ghc-options:
    - -O2
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N

  singular-bench:
    main: singular-bench.hs
    source-dirs:
    - bench
    dependencies:
    - text
    - statistics
    - vector
    - halg-core
    - halg-core-test
    - halg-algorithms
    - halg-bridge-singular
    - mwc-random
    - constraints
    - containers
    - gauge
    - deepseq
    - matrix
    - parallel
    - process
    - sized
    - QuickCheck
    ghc-options:
    - -O2
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N

  singular-heavy-bench:
    main: singular-heavy-bench.hs
    other-modules:
    - Cases
    source-dirs:
    - bench
    - shared
    dependencies:
    - ghc-typelits-knownnat
    - text
    - statistics
    - vector
    - halg-core
    - halg-core-test
    - halg-algorithms
    - halg-bridge-singular
    - vector
    - mwc-random
    - reflection
    - constraints
    - containers
    - gauge
    - deepseq
    - matrix
    - parallel
    - process
    - sized
    - QuickCheck
    ghc-options:
    - -O2
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N

  heavy-bench:
    main:         heavy-bench.hs
    <<: *heavy_bench

  f5-heap-bench:
    buildable: false
    main: f5-heap-bench.hs
    source-dirs:
    - bench
    - shared
    other-modules: Cases
    dependencies:
    - QuickCheck
    - ghc-typelits-knownnat
    - constraints
    - containers
    - deepseq
    - gauge
    - halg-algorithms
    - halg-core
    - halg-core-test
    - vector
    - lens
    - matrix
    - parallel
    - reflection
    - process
    - sized
    ghc-options:
    - -Wall
    - -O2
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N  
