name:                halg-polynomials
version:             0.6.0.0
github:              "konn/halg-polynomials"
license:             BSD3
author:              "Hiromi ISHII"
maintainer:          "konn.jinro _at_ gmail.com"
copyright:           "2018 (c) Hiromi ISHII"

extra-source-files:
- README.md
- ChangeLog.md

tested-with: |
  GHC == 8.4.3, GHC == 8.6.5, GHC == 8.8.2, GHC == 8.10.1

# Metadata used when publishing your package
synopsis: |
  Polynomial rings and basic Gröbner basis computation,  part of halg computational algebra suite.
category:            Math

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the project Web Site <https://konn.github.io/computational-algebra>

dependencies:
- algebraic-prelude
- algebra
- base
- halg-core
- sized

default-extensions:
- CPP
- DataKinds
- FlexibleContexts
- FlexibleInstances
- GADTs
- MultiParamTypeClasses
- OverloadedLabels
- PolyKinds
- TypeFamilies
- TypeInType
- UndecidableInstances  

library:
  source-dirs: src
  ghc-options:
  - -Wall
  - -O2
  - -fplugin Data.Singletons.TypeNats.Presburger
  - -fplugin GHC.TypeLits.KnownNat.Solver
  other-modules:
  - Algebra.Ring.Polynomial.Internal
  dependencies:
  - base >= 4.7 && < 5
  - containers
  - deepseq
  - equational-reasoning
  - ghc-typelits-knownnat
  - strict
  - singletons-presburger
  - hashable
  - heaps
  - lens
  - matrix
  - monad-loops
  - mono-traversable
  - reflection
  - text
  - type-natural
  - unamb
  - unordered-containers
  - vector
  when:
  - condition: impl(ghc >= 9.0)
    then:
      dependencies:
      - singletons >= 3.0
      - singletons-base
    else:
      dependencies:
      - singletons < 3.0
  default-extensions:
  - NoImplicitPrelude


executables: {}
  # halg-polynomials-exe:
  #   main:                Main.hs
  #   source-dirs:         app
  #   ghc-options:
  #   - -Wall
  #   - -threaded
  #   - -rtsopts
  #   - -with-rtsopts=-N
  #   dependencies:
  #   - halg-polynomials

tests:
  halg-polynomials-spec:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -Wall
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    build-tools:
    - tasty-discover
    dependencies:
    - QuickCheck
    - containers
    - halg-core-test
    - halg-polynomials
    - tasty
    - tasty-expected-failure
    - tasty-hunit
    - tasty-quickcheck
    - matrix
    - vector
